
from typing import List

PREDEFINED_TEMPLATES = {
    'imagenet': [
        'a bad photo of a {}.',
        'a photo of many {}.',
        'a sculpture of a {}.',
        'a photo of the hard to see {}.',
        'a low resolution photo of the {}.',
        'a rendering of a {}.',
        'graffiti of a {}.',
        'a bad photo of the {}.',
        'a cropped photo of the {}.',
        'a tattoo of a {}.',
        'the embroidered {}.',
        'a photo of a hard to see {}.',
        'a bright photo of a {}.',
        'a photo of a clean {}.',
        'a photo of a dirty {}.',
        'a dark photo of the {}.',
        'a drawing of a {}.',
        'a photo of my {}.',
        'the plastic {}.',
        'a photo of the cool {}.',
        'a close-up photo of a {}.',
        'a black and white photo of the {}.',
        'a painting of the {}.',
        'a painting of a {}.',
        'a pixelated photo of the {}.',
        'a sculpture of the {}.',
        'a bright photo of the {}.',
        'a cropped photo of a {}.',
        'a plastic {}.',
        'a photo of the dirty {}.',
        'a jpeg corrupted photo of a {}.',
        'a blurry photo of the {}.',
        'a photo of the {}.',
        'a good photo of the {}.',
        'a rendering of the {}.',
        'a {} in a video game.',
        'a photo of one {}.',
        'a doodle of a {}.',
        'a close-up photo of the {}.',
        'a photo of a {}.',
        'the origami {}.',
        'the {} in a video game.',
        'a sketch of a {}.',
        'a doodle of the {}.',
        'a origami {}.',
        'a low resolution photo of a {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'a photo of the clean {}.',
        'a photo of a large {}.',
        'a rendition of a {}.',
        'a photo of a nice {}.',
        'a photo of a weird {}.',
        'a blurry photo of a {}.',
        'a cartoon {}.',
        'art of a {}.',
        'a sketch of the {}.',
        'a embroidered {}.',
        'a pixelated photo of a {}.',
        'itap of the {}.',
        'a jpeg corrupted photo of the {}.',
        'a good photo of a {}.',
        'a plushie {}.',
        'a photo of the nice {}.',
        'a photo of the small {}.',
        'a photo of the weird {}.',
        'the cartoon {}.',
        'art of the {}.',
        'a drawing of the {}.',
        'a photo of the large {}.',
        'a black and white photo of a {}.',
        'the plushie {}.',
        'a dark photo of a {}.',
        'itap of a {}.',
        'graffiti of the {}.',
        'a toy {}.',
        'itap of my {}.',
        'a photo of a cool {}.',
        'a photo of a small {}.',
        'a tattoo of the {}.',
    ],
    'imagenet_select_clip': [
        'a bad photo of the {}.',
        'a photo of the large {}.',
        'a photo of the small {}.',
        'a cropped photo of a {}.',
        'This is a photo of a {}',
        'This is a photo of a small {}',
        'This is a photo of a medium {}',
        'This is a photo of a large {}',
        'This is a masked photo of a {}',
        'This is a masked photo of a small {}',
        'This is a masked photo of a medium {}',
        'This is a masked photo of a large {}',
        'This is a cropped photo of a {}',
        'This is a cropped photo of a small {}',
        'This is a cropped photo of a medium {}',
        'This is a cropped photo of a large {}',
        'A photo of a {} in the scene',
        'a bad photo of the {} in the scene',
        'a photo of the large {} in the scene',
        'a photo of the small {} in the scene',
        'a cropped photo of a {} in the scene',
        'a photo of a masked {} in the scene',
        'There is a {} in the scene',
        'There is the {} in the scene',
        'This is a {} in the scene',
        'This is the {} in the scene',
        'This is one {} in the scene',
        'There is a masked {} in the scene',
        'There is the masked {} in the scene',
        'This is a masked {} in the scene',
        'This is the masked {} in the scene',
        'This is one masked {} in the scene',
    ],
    'imagenet_select': [
        'itap of a {}.',
        'a bad photo of the {}.',
        'a origami {}.',
        'a photo of the large {}.',
        'a {} in a video game.',
        'art of the {}.',
        'a photo of the small {}.',
        'A photo of a {} in the scene',
    ],
    'vild': [
        'a photo of a {}.',
        'This is a photo of a {}',
        'There is a {} in the scene',
        'There is the {} in the scene',
        'a photo of a {} in the scene',
        'a photo of a small {}.',
        'a photo of a medium {}.',
        'a photo of a large {}.',
        'This is a photo of a small {}.',
        'This is a photo of a medium {}.',
        'This is a photo of a large {}.',
        'There is a small {} in the scene.',
        'There is a medium {} in the scene.',
        'There is a large {} in the scene.',
    ],
    'single': [
                'A photo of a {} in the scene',
    ],
}


def get_predefined_templates(template_set_name: str) -> List[str]:
    if template_set_name not in PREDEFINED_TEMPLATES:
        raise ValueError(f'Template set {template_set_name} not found')
    return PREDEFINED_TEMPLATES[template_set_name]
